== Authorization
The authorization decides if a user is allowed to do something. Do something means in Minimal-J execute a
Transaction. Transactions are the communication between the frontend and the backend. This means the
authorization happens when the frontend sends the backend a Transaction to execute. Or in Java: 

[source,java,title="Backend.java"]
----
	[..]
	
	public <T> T doExecute(Transaction<T> transaction) {
		if (Subject.hasRoleFor(transaction)) {
			return transaction.execute();
		} else {
			throw new IllegalStateException(transaction.getClass().getSimpleName() + " forbidden");
		}
	}
----

This seems readable not only for the compiler. The Subject class knows who is logged in (in respect of
the current Thread). It also provides the method to check if a Transaction is allowed.

NOTE: There are two quite similar classes called Subject and User. Subject has more to do with who is
currently logged in and what roles are available. The User class is the model class for the database of
all users and their roles. Minimal-J doesn't depend on the link:http://shiro.apache.org/[Shiro] project but
tries to use more or less the same terminology.

=== Navigation
As you see above the Backend would throw an exception if the logged in user is not allowed to execute a transaction. Of course this should stay an exception. Normally a Frontend should not come to that point.

The application should present a specialized navigation based on the granted roles. This is done with conditions in the Application.getNavigation() method:
[source,java,title="XyApplication.java"]
----
    [..]
    
    @Override
    public List<Action> getNavigation() {
        List<Action> actions = new ArrayList<>();

        if (Subject.hasRole(RosenStaedterAuthorization.ROLE_XY)) {
            ActionGroup actionGroup = new ActionGroup("Xy");
            actionGroup.add(new XyzEditor());
            actions.add(actionGroup);
        }
        [..]
        
        return actions;
    }
----

=== Restrict Transactions
A Transcation can restrict execution to one or more roles by the Role Annotation:
[source,java]
----
@Role("Developer")
public class GenerateDemoDataTransaction implements Transaction<Serializable> {
	[..]
}
----
The Role annotation allows to list more than one role. Execution of the Transaction is granted as long
as the current Subject has *at least one* of the given roles.

=== Restrict entity classes
Not every read or insert needs a specialized Transaction. If you call read or insert on the Backend a generic Transaction is instantiated:
[source,java,title="Backend.java"]
----
	[..]
	
	public static <T> List<T> read(Class<T> clazz, Criteria criteria, int maxResults) {
		List<T> result = execute(new ReadCriteriaTransaction<T>(clazz, criteria, maxResults));
		return result;
	}
----

To restrict access on entities their classes can be annotated
[source,java]
----
@Grant("RoleX")
public class Entity {

	[..]
}
----
If the role name is specified then this role is need for all types of Transactions. For read, insert, update
and delete. But sometimes you may want to restrict only the write access for some user. You can do this by annotate
different roles for the different types of Transactions:
[source,java]
----
@Grant("ReadRole")
@Grant(privilege = Privilege.UPDATE, value = "UpdateRole")
public class Entity {

	[..]
}
----

=== Package wide roles
The needed roles for a Transaction or a business entity can also be specified on a package level. You can
specifiy these roles in the package-info.java file. If you don't know about this file you may have a look at
the link:https://docs.oracle.com/javase/specs/jls/se8/html/jls-7.html[Oracle documentation]. The package-info.java
makes it possible to annotate the package.

The package Annotation only is used if there is no annotation on a class itself. In this way you can specify
the permission for most of your entities on a package level and only annotate the exception in the classes. This
is also a good idea so that you don't forget the permission of new classes.
[source,java,title="package-info.java"]
----
@Grant("pkgRole")
@Grant(privilege = org.minimalj.model.annotation.Grant.Privilege.SELECT, value = "ReadPkgRole")
@Grant(privilege = org.minimalj.model.annotation.Grant.Privilege.UPDATE, value = "UpdatePkgRole")
package org.minimalj.security.permissiontest.pkgrole;

import org.minimalj.model.annotation.Grant;
----
Note that packages don't inherit there roles from their parent package. This would lead to a error-prone complexity.

== Authorization configuration
The Authorization class defines the available users and their roles. There are several specializations to this class:

- The TextFileAuthorization takes a file as input for the users and their passwords. The format of this file is described below.
- The PersistenceAuthorization uses a Persistence instance for that. The Persistence instance can be the one used for all other business entites or a special one.
- The JaasAuthorization connects Minimal-J to the authorization provided by Java itself.

Which one of this specializations is activated is defined via application properties or the application can set the
current Authorization. This method has also the highest priority:

 1. The application sets the Authorization object with the static method setInstance at startup. Note that the Authorization
 object cannot be replaced once it is set. 

 2. The property MjUserFile is set to a file.
 
 3. The property MjJaasConfiguration is set.
 
 4. If nothing from above the Authorization is disabled. The user will not see the login buttons.

=== The user file format
The file defining the users has a special format. The format is very similar to the one used by Shiro.

Every user is defined by a line in the file:
[source,text]
----
MrExample = 2t06hlbF/o+DNhIPmXp2LlZ9B2nre4Mn, j4aSh9OyEfcNNMKZDwJmwRSI/mdwb4yV, Role1, Role2, Role3
----

First there is the name of the user. Followed by '='. The rest of the line is a comma separated list. The first two values are
special. They contain the hashed password and the used salt for the user (encoded with base64). At the end all roles 
granted to this user are listed.

If you wonder how to get the hashed passwords: The TextFileAuthorization class has a main method. Start this class as java
application together with at least two arguments (user and password) and it prints out a line for your user/password file.

=== Login Dialog
If the application is started without authentication then the frontend will not show the user the menu entry (or icon)
to log in. If the authentication is active the frontend must decide if it should confront the user with a login dialog
right on the start or if it is possible to look around without any authentication.
