== Authorization
The authorization decides if a user is allowed to do something. Do something means in Minimal-J execute a
Transaction. Transactions are the communication between the frontend and the backend. This means the
authorization happens when the frontend sends the backend a Transaction to execute. Or in Java: 

[source,java,title="Backend.java"]
----
    [..]

	public <T> T doExecute(Transaction<T> transaction) {
		if (Authorization.isAllowed(transaction)) {
			try {
				currentTransaction.set(transaction);
				return transaction.execute();
			} finally {
				currentTransaction.set(null);
			}
		} else {
			throw new IllegalStateException(transaction.getClass().getSimpleName() + " forbidden");
		}
	}
----

This seems readable not only for the compiler. The Authorization class asks the Subjet class who is logged in (in respect of
the current Thread). It also provides the method to check if a Transaction is allowed.

NOTE: There are two quite similar classes called Subject and User. Subject has more to do with who is
currently logged in and what roles are available. The User class is the model class for the database of
all users and their roles. Minimal-J doesn't depend on the link:http://shiro.apache.org/[Shiro] project but
tries to use more or less the same terminology.

=== Navigation
As you see above the Backend would throw an exception if the logged in user is not allowed to execute a transaction. Of course this should stay an exception. Normally a Frontend should not come to that point.

The application should present a specialized navigation based on the granted roles. This is done with conditions in the Application.getNavigation() method:
[source,java,title="XyApplication.java"]
----
    [..]
    
    @Override
    public List<Action> getNavigation() {
        List<Action> actions = new ArrayList<>();

        if (Subject.hasRole(MyRoles.ROLE_XY)) {
            ActionGroup actionGroup = new ActionGroup("Xy");
            actionGroup.add(new XyzEditor());
            actions.add(actionGroup);
        }
        [..]
        
        return actions;
    }
----

=== Restrict Transactions
A Transcation can restrict execution to one or more roles by the Role Annotation:
[source,java]
----
@Role("Developer")
public class GenerateDemoDataTransaction implements Transaction<Serializable> {
	[..]
}
----
The Role annotation allows to list more than one role. Execution of the Transaction is granted as long
as the current Subject has *at least one* of the given roles.

=== Restrict entity classes
Not every read or insert needs a specialized Transaction. If you call read or insert on the Backend a generic Transaction is instantiated:
[source,java,title="Backend.java"]
----
	[..]
	
	public static <T> List<T> read(Class<T> clazz, Criteria criteria, int maxResults) {
		List<T> result = execute(new ReadCriteriaTransaction<T>(clazz, criteria, maxResults));
		return result;
	}
----

To restrict access on entities their classes can be annotated
[source,java]
----
@Grant("RoleX")
public class Entity {

	[..]
}
----
If the role name is specified then this role is need for all types of Transactions. For read, insert, update
and delete. But sometimes you may want to restrict only the write access for some user. You can do this by annotate
different roles for the different types of Transactions:
[source,java]
----
@Grant("ReadRole")
@Grant(privilege = Privilege.UPDATE, value = "UpdateRole")
public class Entity {

	[..]
}
----

=== Package wide roles
The needed roles for a Transaction or a business entity can also be specified on a package level. You can
specifiy these roles in the package-info.java file. If you don't know about this file you may have a look at
the link:https://docs.oracle.com/javase/specs/jls/se8/html/jls-7.html[Oracle documentation]. The package-info.java
makes it possible to annotate the package.

The package Annotation only is used if there is no annotation on a class itself. In this way you can specify
the permission for most of your entities on a package level and only annotate the exception in the classes. This
is also a good idea so that you don't forget the permission of new classes.
[source,java,title="package-info.java"]
----
@Grant("pkgRole")
@Grant(privilege = org.minimalj.model.annotation.Grant.Privilege.SELECT, value = "ReadPkgRole")
@Grant(privilege = org.minimalj.model.annotation.Grant.Privilege.UPDATE, value = "UpdatePkgRole")
package org.minimalj.security.permissiontest.pkgrole;

import org.minimalj.model.annotation.Grant;
----
Note that packages don't inherit there roles from their parent package. This would lead to a error-prone complexity.

== Authentication
The Authentication class decides if a user may login and keeps track of the currently logged in
users. The most important method is:

[source,java]
----
	public abstract void login(LoginListener loginListener);
----

The specializations of this class define what kind of credentials a user must provide to login (most probably a
user name and a password) and where the list of all users is stored.

The UserPasswordAuthentication is the abstract class which provides the UI action and the transaction to 
implement a simple name/password login. For a more complex Authentication for example with a token sent to
the users phone a different UI would be needed.

The TextFileAuthentication takes a file as input for the users and their passwords. The format of this file is described below.
Small applications with only a few users may want to use this class.

But most applications want to store their users in the database. They can use PersistenceAuthentication or
implement a specialization of UserPasswordAuthentication.

== Authentication configuration

The used Authentication is defined with properties. You see in the
Authentication.create() how this works. 

 1. if the property MjUserFile is set to a file this file should provide user names as (hashed passwords).
 
 2. if MjAuthentication is set then it should be the name of a class extending the Authentication class.
 
 3. If both properties are empty the authentication and authorization is disabled.
 The user will not see the login buttons. In dev mode the user can execute all available transactions.
 But only in dev mode.
 
 
=== The user file format
The file defining the users has a special format. The format is very similar to the one used by Shiro.

Every user is defined by a line in the file:
[source,text]
----
MrExample = 2t06hlbF/o+DNhIPmXp2LlZ9B2nre4Mn, j4aSh9OyEfcNNMKZDwJmwRSI/mdwb4yV, Role1, Role2, Role3
----

First there is the name of the user. Followed by '='. The rest of the line is a comma separated list. The first two values are
special. They contain the hashed password and the used salt for the user (encoded with base64). At the end all roles 
granted to this user are listed.

If you wonder how to get the hashed passwords: The TextFileAuthorization class has a main method. Start this class as java
application together with at least two arguments (user and password) and it prints out a line for your user/password file.

=== Login Dialog
If the application is started without authentication then the frontend will not show the user the menu entry (or icon)
to log in. If the authentication is active the frontend must decide if it should confront the user with a login dialog
right on the start or if it is possible to look around without any authentication. This specification is done
by an override of the <code>isLoginRequired</code> method in the specific application class.
