== Release notes

=== next
* Frontend: Support for delete actions
* Web Frontend: Better detection and support for small devices

=== 0.12.0.0
* Server: use http session or websocket connection as base for session management

=== 0.11.0.1
* Web Frontend: reserve space on the right only if there is a menu
* Renamed main classes to Swing and NanoWebServer
* Search field is disabled if Application doesn't override createSearchPage method

=== 0.10.4.0
* Web Frontend: no type lag if user fills text field faster than server can respond
* SQL persistence: changed semantic of List of identifiables. No containing any more. Update or delete of elements change.
* removed sample names. The examples now use a 3rd party library for that.

=== 0.10.2.0
* Web Frontend: Make dialog button row look better in firefox
* Web Frontend: fixes for FireFox
* Web Frontend: show context actions when open a page
* Web Frontend: No initial alert in Safari

=== 0.10.1.0
* SqlPersistence: fix update of dependables
* Web Frontend: fix right mouse click in detail pages

=== 0.10.0.11

* The rules for the model changed: 'if a business entity has an id field it can have lists'
* Added ajax protocol for json frontend. WebSockets make problems with some firewalls - bad for demos.
* Make servlet more configurable
* Lot of small changes