== Setup

=== Java 8

Minimal-J is based on Java 8. Even if the new language constructs aren't used much yet
there are some jdk classes which are needed. For example LocalDate.

For information about Java and the download of Java see http://java.oracle.com/ . But be aware that you also need
good Java knowledge to use Minimal-J. It's a good idea to learn java by a specific book
before using Minimal-J. Minimal-J uses Java somehow different than other frameworks. As much
as I like that maybe you should know about how it's used elsewhere before learning
the _minimal_ way.

=== Example

You find the examples on https://github.com/BrunoEberhard/minimal-j/tree/master/example[github]
in the example directory. For an easy starts it's best to grab the empty application and
try the stuff explained here and then fill it with your own ideas.

=== Maven

Minimal-J is built with maven and uploaded to the mvnrepository. If you have installed
maven (see https://maven.apache.org/ ) you can download the needed jar automatically by putting
the dependency in the pom.xml of your project.

----
<dependency>
	<groupId>org.minimalj</groupId>
	<artifactId>minimalj</artifactId>
	<version>1.0.0.0</version>
</dependency>
----

If look in the pom.xml of Minimal-J you see that there are some dependencies to 3rd party
libraries. For example:

----
<dependency>
	<groupId>org.apache.derby</groupId>
	<artifactId>derby</artifactId>
	<version>10.11.1.1</version>
	<scope>provided</scope>
</dependency>
----

The apache derby db is used if you want to store your data only in the JVM memory. Have you
noted the scope _provided_? This means that this dependency is not passed to projects with
a dependency to Minimal-J. If you want to use the in memory feature you have to add the
dependency to your project! On the other side if you don't use the feature you don't have
to bother about anything from derby db.

At the moment there a few dependencies you can copy from den Minimal-J pom.xml. Of course
you have to remove the provided scope when doing this.

* Derby DB (with driver)
* The Maria DB JDBC driver
* Lanterna (Terminal UI)

=== Build

You can build your project in the usual maven way

----
mvn clean install
----

=== Start

Then you can start your application with a frontend of your choice. But for some frontend
some preparations must be done. To deploy on web server a WEB-INF directory with a proper web.xml must be configured. Swing and HTML (Json) frontend works out of the box.
This is the reason why I like to start my applications with these frontend so much. You don't need a tomcat and/or all the JEE stuff.

You can put together a correct classpath by yourself or you can delegate this to maven
by using the exec plugin

----
mvn exec:java -Dexec.mainClass="org.minimalj.frontend.impl.swing.Swing" -Dexec.args="org.minimalj.example.empty.EmptyApplication"
----

The web frontend is started the same way.

----
mvn exec:java -Dexec.mainClass="org.minimalj.frontend.impl.nanoserver.NanoWebServer" -Dexec.args="org.minimalj.example.empty.EmptyApplication"
----

Most of the frontends are started like this.

=== Start configuration in pom.xml

The command shell parameters above could also be specified in the pom.xml of your project. This saves you typos and makes it more clear how the application should be
started. You do it by adding the exec maven plugin to the build:

----
<project ...>
	[..]
	<build>
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>1.2.1</version>
				<configuration>
					<mainClass>org.minimalj.frontend.impl.swing.Swing</mainClass>
					<arguments>
						<argument>org.minimalj.example.empty.EmptyApplication</argument>
					</arguments>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		[..]
	</dependencies>
</project>
----

Now you also can start the application from your ide without further configuration.
link:http://stackoverflow.com/questions/6079253/running-maven-exec-plugin-inside-eclipse[Stackoverflow] explains how to do this.

=== Run as servlet

You really don't need a complete application server to run Minimal-J applications. Still you can do it by configuring the
web.xml for your project like this:

----
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://java.sun.com/xml/ns/javaee" xmlns:web="http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
	id="WebApp_ID" version="2.5">
	<display-name>Hello World</display-name>
	<servlet>
		<servlet-name>HelloWorld</servlet-name>
		<servlet-class>org.minimalj.frontend.impl.servlet.MjServlet</servlet-class>
		<init-param>
			<description>Minimal-J application class to start</description>
			<param-name>Application</param-name>
			<param-value>org.minimalj.example.helloworld.HelloWorldApplication</param-value>
		</init-param>
	</servlet>
	<servlet-mapping>
		<servlet-name>HelloWorld</servlet-name>
		<url-pattern>/*</url-pattern>
	</servlet-mapping>
</web-app>
----

All the things that you can with the parameters when you start the application directly you can do by adding the
parameters as init-param. The MjServlet will simply copy all the init-param to system properties (see copyPropertiesFromServletConfigToSystem in MjServlet).

==== MjWebSocketServlet

There is also a class named MjWebSocketServlet in Minimal-J. This provides the WebSocket server if you want to run the web front end not
with the ajax protocol but with WebSockets. Put these lines in your web.xml to activate WebSocket:

----
		<init-param>
			<description>The web front end should us WebSocket for communication</description>
			<param-name>MjUseWebSocket</param-name>
			<param-value>true</param-value>
		</init-param>
----

As you see in the class MjWebSocketServlet the configuration of the WebSocket server is done by annotation. So you don't
need to add another servlet in the web.xml.

Note that the MjWebSocketServlet is not started if there is the 'javax.websocket-api.jar' deployed with your web app see 
http://stackoverflow.com/questions/21852459/tomcat-7-0-50-java-webscoket-implementation-gives-404-error[stackoverflow].
In my workspace the websocket-api jar is deployed even as I set the dependency to provided. In this case you have to set
the included jar for the web application manually.

This applies only for the WebSocket protocol. The ajax protocol will run out of the box.