= Setup

== Java 8

Minimal-J is based on Java 8.

For information about Java and the download of Java see http://java.oracle.com/ . But be aware that you also need
good Java knowledge to use Minimal-J. It's a good idea to learn java by a specific book
before using Minimal-J. Minimal-J uses Java somehow different than other frameworks. As much
as I like that maybe you should know about how it's used elsewhere before learning
the _minimal_ way.

== Eclipse / IDE

Of course Minimal-J can be used with every IDE. Personally I use eclipse. Most of the screenshots
will show eclipse. You can download the latest version of eclipse from https://www.eclipse.org/ .

== Maven 3

Minimal-J uses maven 3 as building tool. In newer eclipse versions maven is already included. If
your IDE has not built in support for maven ou can download maven from https://maven.apache.org/ .

= Create new project

To start a new project simply use the eclipse wizard to create a new maven project.

== Minimal-J dependency

Now you have to add the dependency to Minimal-J in the newly created pom.xml:

----
<dependency>
	<groupId>org.minimalj</groupId>
	<artifactId>minimalj</artifactId>
	<version>1.8.0.0</version>
</dependency>
----

Of course you should replace the version with the newest available.

=== Dependency for Memory DB

If you look in the pom.xml of Minimal-J you see that there are some dependencies to 3rd party
libraries. For example:

----
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <version>1.4.193</version>
	<scope>provided</scope>
</dependency>
----

The h2 db is used if you want to store your data only in the JVM memory. Have you
noted the scope _provided_? This means that this dependency is not passed to projects with
a dependency to Minimal-J. If you want to use the h2 database you have to add the
dependency to your own project. On the other side if you don't use the database you don't have
to bother about anything from h2.

= Build

You can build your project in the usual maven way

----
mvn clean install
----

= Start

Then you can start your application with a frontend of your choice. For some frontend
some preparations must be done. Swing and HTML (Json) frontend works out of the box.
This is the reason why I like to start my applications with these frontend so much. You don't need a tomcat and/or all the JEE stuff.

Standalone frontends provide a class with a main method. These classes need the class name of
your application as argument.

You can put together a correct classpath by yourself or you can delegate this to maven
by using the exec plugin

----
mvn exec:java -Dexec.mainClass="org.minimalj.frontend.impl.swing.Swing" -Dexec.args="org.minimalj.example.empty.EmptyApplication"
----

The web frontend is started the same way.

----
mvn exec:java -Dexec.mainClass="org.minimalj.frontend.impl.nanoserver.NanoWebServer" -Dexec.args="org.minimalj.example.empty.EmptyApplication"
----

Most of the frontends are started like this.

=== Start configuration in pom.xml

The command shell parameters above could also be specified in the pom.xml of your project.
This saves you typos and makes it more clear how the application should be
started. You do it by adding the exec maven plugin to the build:

----
<project ...>
	[..]
	<build>
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>1.2.1</version>
				<configuration>
					<mainClass>org.minimalj.frontend.impl.swing.Swing</mainClass>
					<arguments>
						<argument>org.minimalj.example.empty.EmptyApplication</argument>
					</arguments>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		[..]
	</dependencies>
</project>
----

Now you also can start the application from your ide without further configuration.
link:http://stackoverflow.com/questions/6079253/running-maven-exec-plugin-inside-eclipse[Stackoverflow] explains how to do this.

== Run as servlet

You really don't need a complete application server to run Minimal-J applications. But maybe you are
not able to run standalone applications because your infrastructure only allows to deploy web applications.

There is a special artifact to needed if you want your Minimal-J application to be a servlet. So you can replace
your dependency to Minimal-J with this one:

----
<dependency>
	<groupId>org.minimalj</groupId>
	<artifactId>minimalj_servlet</artifactId>
	<version>1.0.0.0</version>
</dependency>
----

=== Parameters for servlets

If you start your application as a servlet you cannot pass System parameters to configure your Application.
But you can provide a context.xml containing your parameters:

----
<?xml version="1.0" encoding="UTF-8"?>
<Context>
	<Parameter name="MjDevMode" value="true" override="true" />
	<Parameter name="MjSqlDatabase" value="mydb" override="true" />
</Context>
----

This file has to be in the META-INF folder of your web application.

== Run with Springboot

You may have found the springboot project in the ext folder. This can only be used if you want to
use Vaadin as frontend.