== Persistence

Minimal-J doesn't provide a 'complete' Object-relational mapping as you may know it from tools like hibernate.
It's function is reduced to only work with entities following the rules of the Minimal-J models. The
complexity is still high enough. Here a basic example:

[source,java,title="RepositoryExample.java"]
----
package org.minimalj.example.repository;

import [..]

public class RepositoryExample {

	public static void main(String[] args) {
		AbstractTable.sqlLogger.setLevel(Level.FINEST);
		AbstractTable.sqlLogger.getParent().getHandlers()[0].setLevel(Level.FINEST);
		
		SqlRepository repository = new SqlRepository(SqlRepository.embeddedDataSource(), ExamplePerson.class);

		ExamplePerson person = new ExamplePerson();
		person.firstName = "Peter";
		person.lastName = "Muster";
		
		repository.insert(person);
	}
	
	public static class ExamplePerson {
		public static final ExamplePerson $ = Keys.of(ExamplePerson.class);
		public Object id;
		
		@Size(255)
		public String firstName, lastName;
	}
}
----

This example is not a complete Minimal-J application. The repository can be created independently. This
is not the recommended way to use it but it's quite useful for test or example classes.

The first two lines configure the java logging to print out all the execute sql statements. Normally you will
do this with a logging.properties file.

Then the repository is created. It's a persistence layer over a database. As input parameter a DataSource
is needed. DataSource is a JDK class. It is not as popular as the basic JDBC classes and mostly known to be
a tricky configuration point when deploying to a web server. Actually it's not that bad. Read more about it at
oracle https://docs.oracle.com/javase/tutorial/jdbc/basics/sqldatasources.html . 

There are even some helper
methods in Minimal-J that save you all the trouble at the start. In the example an embedded Java DB is used.
You need the derby.jar and derbyclient.jar for that in your classpath. Otherwise you get an exception when
starting the application.

As second argument the SqlRepository constructor needs an Array of the model entities. Or at least of the main
entities. If these main entities reference some list or inline entities that don't need to be listed.

Then an ExamplePerson is constructed and filled and inserted. Here the log from these actions.

[log,txt,title="Log of RepositoryExample"]
----
Aug 05, 2015 9:04:11 AM org.minimalj.backend.sql.LoggingPreparedStatement log
FEIN:    34ms CREATE TABLE EXAMPLE_PERSON (
 id CHAR(36) NOT NULL,
 FIRST_NAME VARCHAR (255) DEFAULT NULL,
 LAST_NAME VARCHAR (255) DEFAULT NULL,
 PRIMARY KEY (id)
)
Aug 05, 2015 9:04:11 AM org.minimalj.backend.sql.LoggingPreparedStatement log
FEIN:    15ms INSERT INTO EXAMPLE_PERSON (FIRST_NAME, LAST_NAME, id) VALUES ('Peter', 'Muster', 'e415162a-4a2e-4df4-a9bc-7ef2638dbe89')
----

=== Field names
Field names in Minimal-J are restricted to the characters a-z, A-Z and 0-9. And here you see why. In the database
the field names are translated to snakeCase (there is a method for it in StringUtils). This means that before every
upper case a underscore is inserted (except for the first letter).

NOTE: There is no consensus in the world of databases what is a valid identifier. Some database allow special characters.
Other do not or require quotation. Most projects take care of that by simply ommit special characters. That's exactly
what Minimal-J is doing. I have never seen a project using umlauts in field names.

=== Very long field names
In databases the length of field names is restricted. Not so much in Java DB or Maria DB. But in Oracle DB the
maximum length of identifiers is 30 characters. In Java there is no such restriction (or at least no noticable one).

Minimal-J could restrict field names according to the databases. But this would make the project more dependend on
the used database. Also the field names grow when translating them to database identifiers (by inserting underscores
before upper case letters and some times by concatinating field names).

Minimal-J chose a different approach. If the field name is too long it is simply cut a the maximum length.
Now what if two field names become equal when cutting them? Then the equal field names are numbered at the end.

You will probably never see this case. If you are interested of how it works have a look at the 
test class SqlLongFieldNameTest.

=== Insert objects
The second log entry shows how the object is added to the table. There is only one part that may surprise you. This is that you
actually see the values. Normally PreparedStatment is used an when logging those you only see something like
(?, ?, ?). Of course Minimal-J does use PreparedStatement (you have to - if you only construct statements out of
a String you have security problems). But the LoggingPreparedStatement does insert the values in the log line.
This can be quite helpfull.

Note that the LoggingPreparedStatement is only implemented as much as Minimal-J needs it. For projects not using
Minimal-J you may have to implement some more overriden methods.


=== Read objects
Minimal-J distinguishes three types of read cases:

1. Read an object by its class and its Id

2. Read one or many objects by more or less complex criteria based on its fields

3. Read objects by a database specific query

The first two types are independend by the used repository. The third is not. You also see this in the  repository class

[source,java,title="Repository.java"]
----
package org.minimalj.backend;

import [..]

public abstract class Repository {
	[..]
	public <T> T read(Class<T> clazz, Object id);
	public <T> List<T> read(Class<T> clazz, Criteria criteria, int maxResults);
	public <T> Object insert(T object);
	public <T> void update(T object);
	public <T> void delete(Class<T> clazz, Object id);
}
----

The first two method correspond to the first to types of read cases.

==== Read objects by Id
This is the most simple case. You have the Id of a business entity and know its class. The repository will
find your object:
[source,java]
----
	Person person = repository.read(Person.class, id);
----
The returned person object will be completely filled with all depending objects and views. If the person contains a
List of addresses this List will be filled. There is no lazy loading in Minimal-J. If you only want a part of the
Person to be loaded you need a View of the Person class.

Where do you get the Repository object? In the example above we created it ourself. But normally the Backend holds
the single instance of of the repository:
[source,java]
----
    Repository repository = Backend.getInstance().getRepository();
	Person person = repository.read(Person.class, id);
----
or in one line:
[source,java]
----
	Person person = Backend.read(Person.class, id);
----
Both versions do exactly the same. The first should not be used. You can decide wether you use the second or the
third version. There is really no reason to have two Repository objects in your application. If you still feel uneasy
to call static methods you can pass around the Repository object. 

==== Read by Criteria
This is the best way to read objects depending on their fields. The most common use of this is probably when you want
to implement a filter for a table. The user may see one or more FormElement to enter values the object he is looking
for should match. This is a code snippet from AccountPositionTablePage:

[source,java]
----
	@Override
	protected List<AccountPosition> load() {
		return Backend.read(AccountPosition.class, By.field(AccountPosition.$.account, account).and(filter), 1000);
	}
----

The second read method in the Repository class takes as second argument a Criteria object. The first one is as for the
other method the class of the read objects. Maybe with some (dirty) magic tricks the class could be retrieved from the criteria
but this wouldn't save much typing and would make the construction of the Criterias much more complex.

At the moment there are two basic criterias. One is FieldCriteria the other SearchCriteria. With FieldCriteria you can limit
the result to objects containing a specific value in one of its field. FieldCriteria has two constructors. The reduced one guesses
you want to be the field to be the exact value. With the extended version you can specify a FieldOperator:

[source,java]
----
	public FieldCriteria(Object key, Object value) {
		this(key, FieldOperator.equal, value);
	}

	public FieldCriteria(Object key, FieldOperator operator, Object value) {
		[..]
	}
----
Normally you will use the factory methods in the By class as you have seen it in the first example about AccountPositions.
This makes the your code shorter and nicer to read.
[source,java]
----
	public static FieldCriteria field(Object key, Object value) {
		return new FieldCriteria(key, value);
	}

	public static FieldCriteria field(Object key, FieldOperator operator, Object value) {
		return new FieldCriteria(key, operator, value);
	}
----

Now the SearchCriteria lets you perform a more fuzzy search. It looks in all fields that have a @Search annotation. If one of the values
is /like/ the specified value than the object is given back as result.

These two basic Criterias can be combined with or and and operators. Just look again at the first example about AccountPositions. There
is another trick. The interface Filter. It's basically a Criteria provider.

At last there is a nice helper method in the By class called range. It can save you a lot of typing:
[source,java]
----
	public static Criteria range(Object key, Object minIncluding, Object maxIncluding) {
		Criteria c = null;
		if (minIncluding != null) {
			c = new FieldCriteria(key, FieldOperator.greaterOrEqual, minIncluding);
		}
		if (maxIncluding != null) {
			c = new FieldCriteria(key, FieldOperator.lessOrEqual, maxIncluding).and(c);
		}
		return c;
	}
----
	
==== Read by query
As nice as the criterias are they have their limits. The query language of a relation database is far mighter than some
simple 'and' and 'or'. Now maybe SQL queries could to translated in their glories to a java expressions. There are projects that do this
(or at least try). I have great respect for them. If you are interested have a look at http://www.jooq.org/ or http://www.querydsl.com/ .
The great appeal of this approach is that you would have static name checks and even some type safety! Why does Minimal-J not go
this way?

* For a great part of your queries it does! Only a small fraction of your reads may need complex queries. For most of them the two read types
we've already seen above will do the trick. And in these two type we have static name checks.

* Personally I like pure SQL more than some fancy DSL. And I think I am not the only developer that doesn't want to learn another concept just
to retrieve some simple data.

* The magic of do everything in java requires some complex transformation classes. This would be against the idea of Minimal-J.

* And yes, I have simply not resources to do something like jOOQ.

I hope you don't think Minimal-J will leave you to work with plain JDBC. Far from that. You will get quite some support for your complex queries. Let's look
at some code from a test class:
[source,java]
----
@Test
	public void testQuery() {
		G g = new G("testName1");
		repository.insert(g);

		g = repository.execute(G.class, "SELECT * FROM G WHERE g LIKE '%N%'");
		Assert.assertNotNull(g);

		g = repository.execute(G.class, "SELECT * FROM " + repository.name(G.class) + " WHERE g LIKE '%am%'");
		Assert.assertNotNull(g);

		g = repository.execute(G.class,
				"SELECT * FROM " + repository.name(G.class) + " WHERE " + repository.name(G.$.g) + " LIKE '%est%'");
		Assert.assertNotNull(g);

		g = repository.execute(G.class,
				"SELECT * FROM " + $(G.class) + " WHERE " + $(G.$.g) + " LIKE '%est%'");
		Assert.assertNotNull(g);
	}
	
	private String $(Object classOrKey) {
		return repository.name(classOrKey);
	}
----
The test method insert a simple test Object to the database. Then it will be read four times. Everytime the same SQL statement will be
executed (except for the searched String).

The first read uses really plain SQL. You can copy the String and paste it in your favorite database explorer tool. I like that. It makes my
life easy. And it's not half as dangerous as you might think. Of course when the name of the class changes the code will break. But
maybe some classes are quite old and will really not be changed anytime soon. Then why bother to write perfect but unhandy code? Discuss
this with your team (and your architect). You should agree when it's allowed to use this type of query definition. And at least all code
that use direct queries should be tested with a unit test!

Now the second definition uses a method on the repository to get the name of the table corresponding to the class. Quite easy to guess how
this works isn't it? In the same way the column name for a field can be looked up. The name method contains some magic that checks if
the argument is a class. If yes the name of the table is returned. Else the name of the field.

The fourth definition uses a trick to further reduce the length of the query definition. It may be too much for you or your
project. Again, discuss this with your team how would like to handle such things. You also may use an other method name for this trick.

=== Optimistic Locking

In some cases you need to detect if two user modify an entity at the same time. Suppose the two user A and B load an entity at
nearly the same time and start editing it. When finished both save the entity. If the implementation doesn't take care of this
situation the user that saves the entity as seconds 'wins'. Meaning his work is saved and the earlier save is overwritten.
Even worse, the first user is not notified that his work is lost.

There are two strategies for this problem. With pessimistic locking an entity is locked as soon as someone is editing it. Nobody else
can enter the edit state. When saved the lock is resolved and the entity is free again. This solution works nice but needs
more work on both implementation and the database. Most of time the other solution is chosen: optimistic locking.

With optimistic locking it's not forbidden to have two user editing the same entity. But when the second user tries to save he
is notified this is not possible. He has to reload the entity and possible do his work again. This sounds harsh but the optimistic
part of this strategy is the belief that this happens very rarly.

Pessimistic locking is not part of Minimal-J. It is looked as a special business case that needs special implementation. Minimal-J
supports (like most other OR-Mapper) only optimistic locking out of the box. You specify an entity to have pessimistic locking
by adding a *version* field. This field counts up with every modification. You can read this field (although you should not
have the need to) but you should not change it as this would mess up the implementation of the optimistic locking.

The test class SqlOptimisticLockingTest uses this entity. The only difference to other entity
classes is the version field. No other special treatment is necessary.

[source,java]
----
public class Q {
	public static final Q $ = Keys.of(Q.class);
	
	public Object id;
	public int version;

	@Size(255)
	public String string;
}
----

One of the tests provokes an exception when trying to update the entity twice without
reading it after the first update:

[source,java]
----
	@Test(expected = Exception.class)
	public void testOptimisticLockingFail() {
		Q q = new Q();
		q.string = "A";
		Object id = repository.insert(q);
		q = repository.read(Q.class, id);
		
		q.string = "B";
		repository.update(q);
		// here the read is forgotten
		
		// this tries to update an old version of q
		q.string = "C";
		repository.update(q);
	}
----

If you activate the sql logging you see what happens. The first update sets the String to 'B' and the version to 1.
The second update doesn't do anything as there is still the where clause 'version = 0'. The missing update
is detected by Minimal-J (in the method updateWithId in the table class).

[log,txt]
----
INSERT INTO Q (STRING, id) VALUES ('A', '1e1ebb02-a604-4ea8-b896-878226aacd5b')
SELECT * FROM Q WHERE id = '1e1ebb02-a604-4ea8-b896-878226aacd5b'
UPDATE Q SET STRING= 'B',  version = version + 1 WHERE id = '1e1ebb02-a604-4ea8-b896-878226aacd5b' AND version = 0
UPDATE Q SET STRING= 'C',  version = version + 1 WHERE id = '1e1ebb02-a604-4ea8-b896-878226aacd5b' AND version = 0
----

=== Technical fields

For an audit trail there are often technical fields on every entity that is persisted in the database. Normally there are
four of them: who created the entity and who changed it together with a timestamp for both. This doesn't produce
a complete audit log but for most use cases its enough.

Minimal-J doesn't determine the exact name of the fields as I didn't found a common standard that would be used
most of the time. Instead fields could annotated with a @TechnicalField. Their value is then automatically generated
when the entity is inserted or updated.

[source, java]
----
public class S {
	public static final S $ = Keys.of(S.class);
	
	public Object id;
	public int version;

	@Size(255)
	public String string;
	
	@TechnicalField(TechnicalFieldType.CREATE_DATE) 
	public LocalDateTime createDate;
	
	@TechnicalField(TechnicalFieldType.CREATE_USER) @Size(255)
	public String createUser;

	@TechnicalField(TechnicalFieldType.EDIT_DATE)
	public LocalDateTime editDate;
	
	@TechnicalField(TechnicalFieldType.EDIT_USER) @Size(255)
	public String editUser;

}
----

This class is used in the JUnit test class SqlTechnicalFieldTest. It contains all four technical fields with the correct
field class. The user fields must be String, the date fields must be LocalDateTime.

Of course normally you would not repeat the four fields in every class but create a mixin class and include it in every
entity:

[source, java]
----
public class TechnicalFields {

	@TechnicalField(TechnicalFieldType.CREATE_DATE) 
	public LocalDateTime createDate;
	
	@TechnicalField(TechnicalFieldType.CREATE_USER) @Size(255)
	public String createUser;

	@TechnicalField(TechnicalFieldType.EDIT_DATE)
	public LocalDateTime editDate;
	
	@TechnicalField(TechnicalFieldType.EDIT_USER) @Size(255)
	public String editUser;
}
----

Note that the following class produces the exact same database schema as the first class. This is because the name of the
mixin field matches the name of the class. This means no prefix is generated for the fields of the mixin class.

[source, java]
----
public class S {
	public static final S $ = Keys.of(S.class);
	
	public Object id;
	public int version;

	@Size(255)
	public String string;
	
	public final TechnicalFields technicalFiels = new TechnicalFields();
}
----

=== Historized entities

If you need a complete audit trail for your entities Minimal-J provides an other possibility. It's called historized
entities. For such entities with every update a new row in the database table is created and the existing one is
not changed (except for the historized flag which is set to true as soon as a newer entity exists).

To activate historization for entity you have to include a special field called historized of class boolean. Yes,
really the primitive type not the class type boolean.

[source, java]
----
public class R {
	public static final R $ = Keys.of(R.class);
	
	public Object id;
	public int version;
	public boolean historized;

	@Size(255)
	public String string;
}
----

You can use this class like any other entity with some exceptions:

* There is a special method on SqlRepository class that can load the history of an entity:
public <T> List<T> loadHistory(Class<?> clazz, Object id, int maxResult) {...}
* Historized entities don't support lazy lists (yet).

Historized entities are somehow against the spirit of Minimal-J. They are a very 'special feature' that could probably
left out. And the feature is not even complete (no lazy lists). But it would be very hard to make the feature
pluggable and one of the bigger examples really need the historization.

But at the end you don't really have to care about historized entities if you don't want use them. 

=== Create tables
Normally when starting an application the database for it already exists. The application should not create the tables
every time it is started. For examples it is actually helpful that the tables are created because otherwise the
examples would fail or get complicated. But how does the persistence layer know if the tables have to be created?

Answer: there is a third parameter in den SqlRepository constructor. It's named createTablesOnInitialize . It's default
is calculated in the method createTablesOnInitialize(DataSource). There you see that the default is exactly made to be
working for examples but in real word applications the tables will not be created.

There is a special main class named TableCreator. This class you will use to initially create a database.

WARNING: There is no check if the used database is a match of the java entities. If you don't newly create the database after
changing a java entity the persistence layer will probably fail with its operations. For small changes (like name
changes) you could manually update the database. For structural changes it's recommended to export the data, delete
the database, and import after the new creation. At the point where this procedure is too expensive you may be
experienced enough to manually update the database even for structural changes.