== Persistence

Minimal-J doesn't provide a 'complete' Object-relational mapping as you may know it from tools like hibernate.
It's function is reduced to only work with entities following the rules of the Minimal-J models. The
complexity is still high enough. Here a basic example:

[source,java,title="PersistenceExample.java"]
----
package org.minimalj.example.persistence;

import [..]

public class PersistenceExample {

	public static void main(String[] args) {
		AbstractTable.sqlLogger.setLevel(Level.FINEST);
		AbstractTable.sqlLogger.getParent().getHandlers()[0].setLevel(Level.FINEST);
		
		SqlPersistence persistence = new SqlPersistence(SqlPersistence.embeddedDataSource(), ExamplePerson.class);

		ExamplePerson person = new ExamplePerson();
		person.firstName = "Peter";
		person.lastName = "Muster";
		
		persistence.insert(person);
	}
	
	public static class ExamplePerson {
		public static final ExamplePerson $ = Keys.of(ExamplePerson.class);
		public Object id;
		
		@Size(255)
		public String firstName, lastName;
	}
}
----

This example is not a complete Minimal-J application. The persistence layer can be created independently. This
is not the recommanded way to use it but it's quite usefull for test or example classes.

The first two lines configure the java logging to print out all the execute sql statements. Normally you will
do this with a logging.properties file.

Then the persistence layer is created. It's a persistence layer over a database. As input parameter a DataSource
is needed. DataSource is a JDK class. It is not as popular as the basic JDBC classes and mostly known to be
a tricky configuration point when deploying to a web server. Actually it's not that bad. Read more about it at
oracle https://docs.oracle.com/javase/tutorial/jdbc/basics/sqldatasources.html . 

There are even some helper
methods in Minimal-J that save you all the trouble at the start. In the example an embedded Java DB is used.
You need the derby.jar and derbyclient.jar for that in your classpath. Otherwise you get an exception when
starting the application.

As second argument the SqlPersistence constructor needs an Array of the model entities. Or at least of the main
entities. If these main entities reference some list or inline entities that don't need to be listed.

Then an ExamplePerson is constructed and filled and inserted. Here the log from these actions.

[log,txt,title="Log of PersistenceExample"]
----
Aug 05, 2015 9:04:11 AM org.minimalj.backend.sql.LoggingPreparedStatement log
FEIN:    34ms CREATE TABLE EXAMPLE_PERSON (
 id CHAR(36) NOT NULL,
 FIRST_NAME VARCHAR (255) DEFAULT NULL,
 LAST_NAME VARCHAR (255) DEFAULT NULL,
 PRIMARY KEY (id)
)
Aug 05, 2015 9:04:11 AM org.minimalj.backend.sql.LoggingPreparedStatement log
FEIN:    15ms INSERT INTO EXAMPLE_PERSON (FIRST_NAME, LAST_NAME, id) VALUES ('Peter', 'Muster', 'e415162a-4a2e-4df4-a9bc-7ef2638dbe89')
----

=== Field names
Field names in Minimal-J are restricted to the characters a-z, A-Z and 0-9. And here you see why. In the database
the field names are translated to snakeCase (there is a method for it in StringUtils). This means that before every
upper case a underscore is inserted (except for the first letter).

NOTE: There is no consensus in the world of databases what is a valid identifier. Some database allow special characters.
Other do not or require quotation. Most projects take care of that by simply ommit special characters. That's exactly
what Minimal-J is doing. I have never seen a project using umlauts in field names.

=== Very long field names
In databases the length of field names is restricted. Not so much in Java DB or Maria DB. But in Oracle DB the
maximum length of identifiers is 30 characters. In Java there is no such restriction (or at least no noticable one).

Minimal-J could restrict field names according to the databases. But this would make the project more dependend on
the used database. Also the field names grow when translating them to database identifiers (by inserting underscores
before upper case letters and some times by concatinating field names).

Minimal-J chose a different approach. If the field name is too long it is simply cut a the maximum length.
Now what if two field names become equal when cutting them? Then the equal field names are numbered at the end.

You will probably never see this case. If you are interested of how it works have a look at the 
test class SqlLongFieldNameTest.

=== Insert objects
The second log entry shows how the object is added to the table. There is only one part that may surprise you. This is that you
actually see the values. Normally PreparedStatment is used an when logging those you only see something like
(?, ?, ?). Of course Minimal-J does use PreparedStatement (you have to - if you only construct statements out of
a String you have security problems). But the LoggingPreparedStatement does insert the values in the log line.
This can be quite helpfull.

Note that the LoggingPreparedStatement is only implemented as much as Minimal-J needs it. For projects not using
Minimal-J you may have to implement some more overriden methods.


=== Read objects
Minimal-J distinguishes three types of read cases:

1. Read an object by its class and its Id

2. Read one or many objects by more or less complex criteria based on its fields

3. Read objects by a database specific query

The first two types are independend by the used persistence layer. The third is not. You also see this in the 
persistence interface

[source,java,title="Persistence.java"]
----
package org.minimalj.backend;

import [..]

public interface Persistence {
	public <T> T read(Class<T> clazz, Object id);
	public <T> List<T> read(Class<T> clazz, Criteria criteria, int maxResults);
	public <T> Object insert(T object);
	public <T> T update(T object);
	public <T> void delete(Class<T> clazz, Object id);
}
----

The first two method correspond to the first to types of read cases.

==== Read objects by Id
This is the most simple case. You have the Id of a business entity and know its class. The persistence layer will
find your object:
[source,java]
----
	Person person = persistence.read(Person.class, id);
----
The returned person object will be completly filled with all depending objects and views. If the person contains a
List of addresses this List will be filled. There is no lazy loading in Minimal-J. If you only want a part of the
Person to be loaded you need a View of the Person class.

Where do you get the Persistence object? In the example above we created it ourself. But normally the Backend holds
the single instanceof of the persistence:
[source,java]
----
    Persistence persistence = Backend.getInstance().getPersistence();
	Person person = persistence.read(Person.class, id);
----
or with the shortcut:
[source,java]
----
    Persistence persistence = Backend.persistence();
	Person person = persistence.read(Person.class, id);
----
or in one line:
[source,java]
----
	Person person = Backend.read(Person.class, id);
----
All 3 versions do exactly the same. The first should not be used. You can decide wether you use the second or the
third version. There is really no reason to have two Persistence objects in your application. If you still feel uneasy
to call static methods you can pass around the Persistence object. 

==== Read by Criteria
This is the best way to read objects depending on thier fields. The most common use of this is probably when you want
to implement a filter for a table. The user may see one or more FormElement to enter values the object he is looking
for should match. This is a code snippet from AccountPositionTablePage:

[source,java]
----
	@Override
	protected List<AccountPosition> load() {
		return Backend.read(AccountPosition.class, By.field(AccountPosition.$.account, account).and(filter), 1000);
	}
----

The second read method in the Persistence interface takes as second argument a Criteria object. The first one is as for the
other method the class of the read objects. Maybe with some (dirty) magic tricks the class could be retrieved from the criteria
but this wouldn't save much typing and would make the construction of the Criterias much more complex.

At the moment there are two basic criterias. One is FieldCriteria the other SearchCriteria. With FieldCriteria you can limit
the result to objects containing a specific value in one of its field. FieldCriteria has two constructors. The reduced one guesses
you want to be the field to be the exact value. With the extended version you can specify a FieldOperator:

[source,java]
----
	public FieldCriteria(Object key, Object value) {
		this(key, FieldOperator.equal, value);
	}

	public FieldCriteria(Object key, FieldOperator operator, Object value) {
		[..]
	}
----
Normally you will use the factory methods in the By class as you have seen it in the first example about AccountPositions.
This makes the your code shorter and nicer to read.
[source,java]
----
	public static FieldCriteria field(Object key, Object value) {
		return new FieldCriteria(key, value);
	}

	public static FieldCriteria field(Object key, FieldOperator operator, Object value) {
		return new FieldCriteria(key, operator, value);
	}
----

Now the SearchCriteria lets you perform a more fuzzy search. It looks in all fields that have a @Search annotation. If one of the values
is /like/ the specified value than the object is given back as result.

These two basic Criterias can be combined with or and and operators. Just look again at the first example about AccountPositions. There
is another trick. The interface Filter. It's basically a Criteria provider.

At last there is a nice helper method in the By class called range. It can save you a lot of typing:
[source,java]
----
	public static Criteria range(Object key, Object minIncluding, Object maxIncluding) {
		Criteria c = null;
		if (minIncluding != null) {
			c = new FieldCriteria(key, FieldOperator.greaterOrEqual, minIncluding);
		}
		if (maxIncluding != null) {
			c = new FieldCriteria(key, FieldOperator.lessOrEqual, maxIncluding).and(c);
		}
		return c;
	}
----
	
==== Read by query
As nice as the criterias are they have their limits. The query language of a relation database is far mighter than some
simple 'and' and 'or'. Now maybe SQL queries could to translated in their glories to a java expressions. There are projects that do this
(or at least try). I have great respect for them. If you are interested have a look at http://www.jooq.org/ or http://www.querydsl.com/ .
The great appeal of this approach is that you would have static name checks and even some type safety! Why does Minimal-J not go
this way?

* For a great part of your queries it does! Only a small fraction of your reads may need complex queries. For most of them the two read types
we've already seen above will do the trick. And in these two type we have static name checks.

* Personally I like pure SQL more than some fancy DSL. And I think I am not the only developer that doesn't want to learn another concept just
to retrieve some simple data.

* The magic of do everything in java requires some complex transformation classes. This would be against the idea of Minimal-J.

* And yes, I have simply not resources to do something like jOOQ.

I hope you don't think Minimal-J will leave you to work with plain JDBC. Far from that. You will get quite some support for your complex queries. Let's look
at some code from a test class:
[source,java]
----	
	@Test
	public void testQuery() {
		G g = new G("testName1");
		persistence.insert(g);

		g = persistence.execute(G.class, "SELECT * FROM G WHERE g LIKE '%N%'");
		Assert.assertNotNull(g);

		g = persistence.execute(G.class, "SELECT * FROM " + persistence.name(G.class) + " WHERE g LIKE '%am%'");
		Assert.assertNotNull(g);

		g = persistence.execute(G.class,
				"SELECT * FROM " + persistence.name(G.class) + " WHERE " + persistence.name(G.$.g) + " LIKE '%est%'");
		Assert.assertNotNull(g);

		g = persistence.execute(G.class,
				"SELECT * FROM " + $(G.class) + " WHERE " + $(G.$.g) + " LIKE '%est%'");
		Assert.assertNotNull(g);
	}
	
	private String $(Object classOrKey) {
		return persistence.name(classOrKey);
	}
----
The test method insert a simple test Object to the database. Then it will be read four times. Everytime the same SQL statement will be
executed.

The first read uses really plain SQL. You can copy the String and paste it in your favorite database explorer tool. I like that. It makes my
life easy. And it's not half as dangerous as you might think. Of course when the name of the class changes the code will break. But
maybe some classes are quite old and will really not be changed anytime soon. Then why bother to write perfect but unhandy code? Discuss
this with your team (and your architect). You should agree when it's allowed to use this type of query definition. And at least all code
that use direct queries should be tested with a unit test!

Now the second definition uses a method on the persistence to get the name of the table corresponding to the class. Quite easy to guess how
this works isn't it? In the same way the column name for a field can be looked up. The name method contains some magic that checks if
the argument is a class. If yes the name of the table is returned. Else the name of the field.

The fourth definition uses a trick to further reduce the length of the query definition. It may be too much for you or your
project. Again, discuss this with your team how would like to handle such things. You also may use an other method name for this trick.

TODO: describe handle of Integer.class

=== Create tables
Normally when starting an application the database for it already exists. The application should not create the tables
every time it is started. For examples it is actually helpfull that the tables are created because otherwise the
examples would fail or get complicated. But how does the persistence layer know if the tables have to be created?

Answer: there is a third parameter in den SqlPersistence constructor. It's named createTablesOnInitialize . It's default
is calculated in the method createTablesOnInitialize(DataSource). There you see that the default is exactly made to be
working for examples but in real word applications the tables will not be created.

There is a special main class named TableCreator. This class you will use to initially create a database.

WARNING: There is no check if the used database is a match of the java entities. If you don't newly create the database after
changing a java entity the persistence layer will probably fail with its operations. For small changes (like name
changes) you could manually update the database. For structural changes it's recommanded to export the data, delete
the database, and import after the new creation. At the point where this procedure is too expensive you may be
enough experienced that you can manually update the database even for structural changes.