== Pet Clinic

(This text is not yet complete)

The pet clinic demo application was published by the spring framework. It is probably meant to be
a distant relative to Sun's pet store. The pet store was abonded by Sun and Oracle long ago but the
pet clinic demo ist still active. I have to admit that the pet clinic also fits the capabilities of
Minimial-J much better. The pet store heavily uses things like uploads and images. Things that aren't
implemented at the moment where I write this documentation.

The source of the original pet clinic can be found https://github.com/spring-projects/spring-petclinic[on github] .
It can be downloaded and started very easely. Two command lines and the server runs (as long as you
have maven and java previously installed). Kind of the minimal way ;) On the other hand the single
maven command downloads quite a bunch of jars. My local maven repository grew around 30MB.

If you don't want to install the original demo: I have found a running instance
at http://petclinic.cloudapp.net/ .

Let's minimize this application!

=== The model

The data model is always a good point to understand how an application 'ticks'. There are 10
classes in the package org.springframework.samples.petclinic .

Two classes will not exist in Minimal-J: BaseEntity simply defines the id field. In Minimal-J every
persisted entity class must have an id field. No need for a BaseEntity. 

Then there is the NamedEntity. It defines a single field called name. No surprise here. What
I wouldn't have guessed that only three entity classes extend from NamedEntity: Pet, PetType and
Speciality. The Owner entity doesn't extend from NamedEntity. Although you might think an Owner
has a name too! This shows again how rarly a class hierarchy is usefull in a real world application.
Of course the owners will have a name. But for humans there are other 'names' than for pets.

In Minimal-J an entity class must not extend another class. That's not so bad here. It's only
about one field. Not much code duplication here.

But there is a second extension: Both Owner and Vet extend from Person. Again: no extension of entity
classes in Minimal-J. Still we don't need to duplicate all the fields of Person. We simply use
the Person class as inline field in Owner and in Vet:

[source,java,title="Owner.java"]
----
package org.minimalj.example.petclinic.model;

import [..]

public class Owner implements Rendering, Mocking {
    public static final Owner $ = Keys.of(Owner.class);
	
    public Object id;
	
    public final Person person = new Person();
	
    @NotEmpty @Size(255)
    public String address;

    @NotEmpty @Size(80)
    public String city;

    @NotEmpty @Size(20)
    public String telephone;
    
    public List<Pet> getPets() {
    	if (Keys.isKeyObject(this)) return Keys.methodOf(this, "pets", List.class);
    	return Backend.persistence().read(Pet.class, Criteria.equals(Pet.$.owner, this), 100);
	}
    
    @Override
    public String render(RenderType renderType) {
    	return person.render(renderType);
    }
    
    @Override
    public void mock() {
    	[..]
    }
}
----

The first lines are maybe to one to be explaind. First the declaration of the
$ constant. This constant is used to specificy the Form layout and some other places
were a field can be referenced. It's important to declare this constant final and
static. The persistence layer checks this at startup and throws an exception if a
model entity doesn't follow all the rules by Minimal-J.

The id field is as always of class Object. This means the persistence layer is free to use what
it likes as id class. Most probably it will be a UUID but that's up to the persistence
layer.

The person field is declared final and must be initiallized. This means the Person is
used as inline field. Inline fields don't get a DB table of their one. Their fields are
added to the entity where the inline is used. The owner table looks like this:

[source,sql,title="Log of table creation"]
----
CREATE TABLE OWNER (
 id CHAR(36) NOT NULL,
 FIRST_NAME VARCHAR (30) NOT NULL,
 LAST_NAME VARCHAR (30) NOT NULL,
 ADDRESS VARCHAR (255) NOT NULL,
 CITY VARCHAR (80) NOT NULL,
 TELEPHONE VARCHAR (20) NOT NULL,
 PRIMARY KEY (id)
) 
----

As the field person has the same name as its class the names don't have a prefix (in case you
wonder what will happen if an inline Class is used twice). Inlines are good replacement
for inheritence ('has a' instead of 'is a'). Even better you can inline more than one
inline and you get kind of multiple inheritence. Maybe it's more like 'traits' in Scala.

The String fields are easy. All of them are required. Their maximum size must be specified
or the persistence layer will complain.

Then there is the getPets method. Basically it should declare a kind of a virtual field. This
field is not persisted directly. But a persistence operation is execute if the method is called.
This explanins the second line.

The first line exists only for the Minimal-J framework. It is necessary for the magic in the
$ constant. It makes it possible to write Owner.$.getPets() as a reference to a virtual
field. You don't have to unterstand exactly how this works. But it's important that you
use the line correctly. The pattern is:
[source,java]
----
 if (Keys.isKeyObject(this)) return Keys.methodOf(this, NAME_OF_METHOD, RETURN_TYPE.class);
----

[source,java,title="Vet.java"]
----
package org.minimalj.example.petclinic.model;

import [..]

public class Vet {
	public static final Vet $ = Keys.of(Vet.class);
	
	public Object id;
	
	public final Person person = new Person();
	
    public final Set<Specialty> specialties = new HashSet<>();
}
----

The $ constant and the id of class Object are getting familiar. Then again the Vet class makes
use of a Person as a inline Object.  Only the last field is somehow new. It's a (final) Set of
an enum class. In the framework this Set is mapped to an Integer. This is way the enum class
can have at most 32 values.

[source,java,title="Speciality.java"]
----
package org.minimalj.example.petclinic.model;

public enum Specialty {
	radiology, surgery, dentistry;
}
----

Speciality is declared as an enum in this example. In a real world application it might be rather
be declared as a Code. Enum values can only be changed by changing the class. Codes can be
added at runtime. But as codes cannot be used as elements of a 'final Set' the model gets more
complicate.

To explain this: what if vets could only treat certain types of pets? You would need an additional
class:
[source,java]
----
public class TreatablePet {
	public PetType petType;
}
----
Note that there is no id field in TreatablePet. TreatablePet is a completly depended on the Vet class.
The field would be declared as 
[source,java]
----
    public final List<TreatablePet> treatablePet = new ArrayList<>();
----
Such a list is only allowed because TreatablePet doesn't contain an id field. Entities cannot contain
other entities directly. This is to avoid slow loading operations and logical problems when
updating entities.

Now for the PetType entity. This is an example for a Code:
[source,java,title="PetType.java"]
----
package org.minimalj.example.petclinic.model;

import [..]

public class PetType implements Code, Rendering {
	public Object id;

	@NotEmpty @Size(80)
	public String name;
	
	@Override
	public String render(RenderType renderType) {
		return name;
	}
}
----
An entity is declared to be a Code by implementing the Code interface. The Code interface is an
extension of the View interface. But both interfaces are marker interface. They declare not
methods or constants at all. So why bother? Because of how codes are treated by the persistence
layer.

When an entity is inserted or updated and this entity contains a Code then this Code itself is
not touched by this operation. Meaning the frontend could have changed the name of the PetType
before setting it to the pet. Then send it to the backend for persisting. The pet would still
referered as the original type.

NOTE: This behavior is always important to remember. It stands for codes but also for views. Actually it's
the main behavior of views. Views are normally are parts of normal entities (selected non-list fields). Codes are like 
'views on themself' (this is also the reason why the Code interface overrides the generic of the
View interface).

Codes have another speciality. Their initial values can be specified. This can happen in two ways.
The first one is to have a csv - file with the same name in the same package as the Code class
itself. For the PetClinic example I use this method. The csv file has this content:
----
name
Cat
Dog
Lizard
Snake
Bird
Hamster
----
The first line declares the field names to be filled. Than simply the instances are listed.

Then there is a second way to declare fields. That way is to prefered when the values of the codes
are used in the application code itself. In the PetClinic we don't need this. For example we don't
have a restricition that a visit can only be entered for a specific PetType.

Still here the example of such a Code declaration:
[source,java]
----
package org.minimalj.example.petclinic.model;

import [..]

public class PetType implements Code, Rendering {

	public Object id;

	public static final PetType mouse = new PetType("Mouse");
	
	public PetType() {
	}
	
	public PetType(String name) {
		this.name = name;
	}
	
	[..]
}
----
The declaration is only one line but because now there is a constuctor with an argument the constructor
without arguments has to be declared too to stay public accessible. The framework looks in the Code
classes for public static final declarations of objects of the right class. These are recognized as
needed constants.

Both types of initial values are created when the database table is created. The two types of
initival values declaration can also be mixed.

=== The pages and editors

All the frontend stuff is in the package org.minimalj.example.petclinic.frontend . In a larger project you
could hold separate packages for editors and pages. Or you could do the packaging more according to the
business areas. It's up to you.

=== Owner search page

The OwnerSearchPage is a SimpleSearchPage. Why simple? Because the objects displayed are not a reduced version
but the business entities itself. For complex entities with lots of depending objects it's a good idea to
have a search entitiy (a view) of the complex entitiy. So you load only a small part of the data. Then when
the user wants to display a single entity in its full beauty you have to reload the entity with all depending
objects. Obviously for that you have to have two classes and the SearchPage needs exactly these two classes
as generic types.

But as said the owner search page is simple and doesn't separate the type of the displayed object from the type
of a possible detail.
[source,java,title="OwnerSearchPage.java"]
----
package org.minimalj.example.petclinic.frontend;

import [..];

public class OwnerSearchPage extends SimpleSearchPage<Owner> {
	private static final Object[] keys = {Owner.$.person.getName(), Owner.$.address, Owner.$.city, Owner.$.telephone};
	
	public OwnerSearchPage(String query) {
		super(query, keys);
	}

	@Override
	protected List<Owner> load(String query) {
		return Backend.persistence().read(Owner.class, Criteria.search(query), 100);
	}

	@Override
	public ObjectPage<Owner> createDetailPage(Owner owner) {
		return new OwnerPage(owner);
	}
}
----
In the constructor the query entered by the user is passed to the super class together with the key used for the
columns in the table. The load method needs as its name says load the entities displayed in the result table.
Maybe this method could be provided by the abstract search page. But then the OwnerSearchPage would not be very
readable. It wouldn't be clear what exactly this page does. There is still enough magic here. Because how does
the backend know in which fields it has to search for the given String? This is specified by the @Search
annotation in the Person class:
[source,java]
----
	@NotEmpty @Size(30) @Searched
	public String firstName, lastName;
----
The last method of OwnerSearchPage returns the page to be displayed when the user activates a single result. In
most frontends this means the user has double clicked on a row.


=== Comparison Spring vs. Minimal-J

To be written

The owner class in the spring version can be found https://github.com/spring-projects/spring-petclinic/blob/master/src/main/java/org/springframework/samples/petclinic/model/Owner.java[here].
